### ISSUE TITLE
Failed to deply directly from github

### ISSUE THREAD

**Issue by juanjo-s2** [miguelangelopereira/azuremonitor2syslog#2]
I'm experiencing problems running the function deployed directly from github. It looks like a library is missing.

```
Error:

Function (AzureMonitor2Syslog) Error: The binding type(s) 'eventHubTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.

```
Is there any way to include the "Microsoft.Azure.WebJobs.Extensions.EventHubs" package as dependency?

**Comment by miguelangelopereira** [comment]
As a workaround. See this: https://github.com/Azure/azure-functions-host/wiki/Updating-your-function-app-extensions

I'm going to see what needs to be changed for that dependency.

**Comment by adrianwells** [comment]
@juanjo-s2 and @miguelangelopereira - Hello. Is there an update to this? Following the notes [README.md](https://github.com/miguelangelopereira/azuremonitor2syslog/blob/master/README.md) which looks to be same here, was able to get this to get past this error after making sure the path to npm was available and that seems to be a workaround.

**Comment by miguelangelopereira** [comment]
For now we need to use the app extensions
