### ISSUE TITLE
Updating the Cardinality to many so the EventMessage.foreach function will work

### ISSUE THREAD

**Issue by jcbrooks92** [miguelangelopereira/azuremonitor2syslog#6]
You may receive the error below because the myEventHubMessage is not an array of messages but a single message. You need to update the cardinality to **many**.

> To receive events in a batch, set cardinality to many in the function.json file, as shown in the following examples.

{
  "type": "eventHubTrigger",
  "name": "eventHubMessages",
  "direction": "in",
  "eventHubName": "MyEventHub",
  **"cardinality": "many",**
  "connection": "myEventHubReadConnectionAppSetting"
}

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#version-2x-3

> Error
> 2019-07-24T18:48:35.475 [Error] Executed 'Functions.AzureMonitor2Syslog'  (Failed, Id=xxxx)Result:  FailureException: TypeError: myEventHubMessage.forEach is not a  functionStack: TypeError: myEventHubMessage.forEach is not a functionat  module.exports  (D:\\home\\site\\wwwroot\\AzureMonitor2Syslog\\index.js:51:23)
> --

**Comment by miguelangelopereira** [comment]
Thanks for this comment. I'll update the guidance.
