### ISSUE TITLE
Connection to Event hub

### ISSUE THREAD

**Issue by scottsciarrino** [miguelangelopereira/azuremonitor2syslog#8]
I'm not  that familiar with app services, I think I have it setup right but not pushing any data. 
I added the variables, change the one setting in integrate section,  (should be the name of the 
Event Hubs Namespace or instance?) then added the eventhub function.  but no output.
Then under the function integrate I was able to drop down and pick the an Event Hub connection even tho it said that it was read only..  Any Ideas?
Thanks

**Comment by miguelangelopereira** [comment]
Hey. If you are not familiar what I recommend is to start with a Windows hosted function and choose the template event hub trigger. It will guide your thought the connections. then just paste js code in. Let me know
